---
abstract: ~
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-MicroTurtle
no_index:
  directory:
    - inc
    - t
recommends:
  HTML::Microformats: 0
requires:
  CGI::Util: 0
  Data::UUID: 0
  Digest::SHA1: 0
  LWP::UserAgent: 0
  RDF::Trine: 0.123
  RDF::TrineShortcuts: 0
  Text::Balanced: 0
  URI: 0
  XML::Atom::OWL: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-MicroTurtle
  homepage: http://search.cpan.org/dist/RDF-MicroTurtle/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-MicroTurtle/
version: 0.001
